### ISSUE TITLE
Create a README.md file

### ISSUE THREAD

**Issue by aswnss-m** [aswnss-m/python_projects#2]
This repo need a readme.md file .

About: This repo is for showcasing beginner-indermediate level python projects, 
The readme file should be astheticaly pleasing.. use of emoticons are apreciated. 
Should be short and simple .
Also throw a motivational quote in there (related to programming ofcourse)

**Comment by bibliofilo** [comment]
Hi, went ahead and added content to the README page, are the program descriptions ok? #4

**Comment by aswnss-m** [comment]
Love your work man , keep it going .

**Comment by bibliofilo** [comment]
Thanks, it was fun! I know it's closed, but any chance this could get labeled with the hacktoberfest tag?
